version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build: .
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432/test
    volumes:
      - .:/app
    ports:
      - '8181:8181'
    depends_on:
      - db
volumes:
  db-data:
